[project]
site_name = "SCP:RP Addon Docs"
site_url = "https://cifiuqa.github.io/scprp-docs"
site_description = "Documentation for SCP:RP Addons, maintained by The Aquifer."
site_author = "The Aquifer"

nav = [
    {"Introduction" = "index.md"},
    {"Documentation" = [
        "scprp/index.md",
        {"SCP:RP Functions" = "scprp/functions.md"},
        {"Roblox Integration" = "scprp/roblox.md"},
        {"Limitations" = "scprp/limitations.md"}
    ]}
]

extra_css = ["stylesheets/extra.css"]

copyright = """Maintained with love by <a href='https://discord.gg/xAU96USgBv' target='_blank'>The Aquifer</a>. Powered by <a href='https://zensical.org' target='_blank'>Zensical</a>."""

[project.theme]
palette.scheme = "slate"
palette.primary = "custom"
palette.accent = "custom"

font.code = "Roboto Mono"

language = "en"

logo = "images/logo.png"
favicon = "images/logo.png"


features = [
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.tracking",
    "navigation.sections",
    "navigation.path",
    "navigation.indexes",
    "navigation.top",
    "toc.follow"
]

[project.extra]
generator = false

[[project.extra.social]]
icon = "fontawesome/brands/discord"
link = "https://discord.gg/xAU96USgBv"
name = "The Aquifer on Discord"

[project.markdown_extensions.toc]
toc_depth = 3

[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions.attr_list]

[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

[project.theme.icon.admonition]
note = "fontawesome/solid/note-sticky"
abstract = "fontawesome/solid/book"
info = "fontawesome/solid/circle-info"
tip = "fontawesome/solid/bullhorn"
success = "fontawesome/solid/check"
question = "fontawesome/solid/circle-question"
warning = "fontawesome/solid/triangle-exclamation"
failure = "fontawesome/solid/bomb"
danger = "fontawesome/solid/skull"
bug = "fontawesome/solid/robot"
example = "fontawesome/solid/flask"
quote = "fontawesome/solid/quote-left"
